/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comucacaoarduino;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Eder
 */
public class FrmLed extends javax.swing.JFrame {

    ControleLed arduino = new ControleLed();

    /**
     * Creates new form FrmLed
     */
    public FrmLed() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLigaLed = new javax.swing.JButton();
        btnDesligaLed = new javax.swing.JButton();
        tbtnONOFF = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        RbtnPiscaLed = new javax.swing.JRadioButton();
        LsdLed = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLigaLed.setText("Liga");
        btnLigaLed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLigaLedActionPerformed(evt);
            }
        });

        btnDesligaLed.setText("Desliga");
        btnDesligaLed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesligaLedActionPerformed(evt);
            }
        });

        tbtnONOFF.setText("ON");
        tbtnONOFF.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tbtnONOFFAncestorRemoved(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tbtnONOFFAncestorMoved(evt);
            }
        });
        tbtnONOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnONOFFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("Controle de Led");

        jLabel2.setText("Botão ON/OFF");

        jLabel3.setText("Botão Liga");

        jLabel4.setText("Botão Desliga");

        RbtnPiscaLed.setText("Pisca Led");
        RbtnPiscaLed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnPiscaLedActionPerformed(evt);
            }
        });

        LsdLed.setMaximum(1000);
        LsdLed.setMinimum(400);
        LsdLed.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                LsdLedCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbtnONOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLigaLed, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(RbtnPiscaLed))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btnDesligaLed, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LsdLed, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnONOFF))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLigaLed)
                            .addComponent(btnDesligaLed))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LsdLed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbtnPiscaLed))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesligaLedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesligaLedActionPerformed
        try {
            arduino.DesligaLed();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmLed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDesligaLedActionPerformed

    private void btnLigaLedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLigaLedActionPerformed
        try {
            arduino.LigaLed();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmLed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLigaLedActionPerformed

    private void tbtnONOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnONOFFActionPerformed
        if (this.tbtnONOFF.isSelected()) {
            try {
                arduino.LigaLed();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FrmLed.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.tbtnONOFF.setText("OFF");
        } else {
            try {
                arduino.DesligaLed();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FrmLed.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.tbtnONOFF.setText("ON");
        }
    }//GEN-LAST:event_tbtnONOFFActionPerformed

    private void tbtnONOFFAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbtnONOFFAncestorMoved

    }//GEN-LAST:event_tbtnONOFFAncestorMoved

    private void tbtnONOFFAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbtnONOFFAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnONOFFAncestorRemoved

    private void RbtnPiscaLedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnPiscaLedActionPerformed
        try {
            if (this.RbtnPiscaLed.isSelected()) {
                arduino.PiscaLed();
            } else {
                arduino.DesligaLed();
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmLed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RbtnPiscaLedActionPerformed

    private void LsdLedCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_LsdLedCaretPositionChanged
        try {
            slider();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmLed.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LsdLedCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider LsdLed;
    private javax.swing.JRadioButton RbtnPiscaLed;
    private javax.swing.JButton btnDesligaLed;
    private javax.swing.JButton btnLigaLed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton tbtnONOFF;
    // End of variables declaration//GEN-END:variables


    public void slider() throws FileNotFoundException{
        int slider = LsdLed.getValue();
        ControleLed objteste = new ControleLed();
        objteste.VeloLed(slider);        
    }

}
